### ISSUE TITLE
Missing export `id` (1.8.0)

### ISSUE THREAD

**Issue by Evertt** [bricksoft/deno_tags#1]
I import like this:

```typescript
import { oneLine, stripIndents } from "https://deno.land/x/deno_tags@1.8.0/tags.ts"
```

And I get this error, pointing to [this file](https://github.com/bricksoft/deno_tags/blob/1.8.0/lib/tags/id.ts#LL1):

```
error: Uncaught SyntaxError: The requested module 'https://cdn.esm.sh/common-tags@1.8.0' does not provide an export named 'id'
import { id as _id } from "https://cdn.esm.sh/common-tags@1.8.0";
```

I don't understand how this ever worked, because you pinned the version number in `"https://cdn.esm.sh/common-tags@1.8.0"` to `1.8.0`, so I would expect that if this worked when you tested it 2 years ago, that it should still be working...

But anyway, can you try to fix it? 🙏

**Comment by peanutbother** [comment]
I did a few mistakes back then and forgot about them.
They should all be fixed by now with the new release I pushed.

Let me know if problems persist :)
